# Generated by Django 3.2.5 on 2021-07-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='user_id',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='user_name',
            field=models.CharField(max_length=256),
        ),
    ]
