# Generated by Django 3.2.5 on 2021-07-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20210709_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
